Automatically create PR to update JSON when E2E course-info failed (#411)
### Summary

This pull request tries to let @dti-github-bot automatically create a PR when the E2E test on course info json failed. I hope this can reduce our burden to update stuff.
Ideally, we can show the diff inline in the created PR comment, but it might us to switch the entire workflow to github actions. It's not too bad to look at the latest master E2E test failure to see what's changed, so I decide not to implement it, as least in this diff.

### Test Plan

See CI running result. The PR is created in https://github.com/cornell-dti/samwise/pull/412.
The consistency test is designed to fail, so that the PR creation job can be triggered. The create PR job also fails because the PR is already created. This error cannot be try-catched, but I don't think it's too big because it can remind people to review PRs. :)

diff --git a/.github/workflows/e2e-course-info.yml b/.github/workflows/e2e-course-info.yml
--- a/.github/workflows/e2e-course-info.yml
+++ b/.github/workflows/e2e-course-info.yml
@@ -15,6 +15,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
+        with:
+          fetch-depth: 0
+          token: ${{ secrets.BOT_TOKEN }}
       - name: Set up Node 10
         uses: actions/setup-node@master
         with:
@@ -37,3 +40,33 @@ jobs:
           cat frontend/src/assets/json/sp20-courses-with-exams-min.json | jq 'sort_by(.courseNumber)' > b.json
       - name: Compare JSON against current JSON
         run: diff a.json b.json
+      - name: Automatically create commit if JSON is different
+        if: failure()
+        run: |
+          git config --global user.name "dti-github-bot"
+          git config --global user.email "admin@cornelldti.org"
+          BRANCH="dti-github-bot/update-course-json"
+          rm a.json b.json
+          cp course-info/sp20-courses-with-exams-min.json frontend/src/assets/json/
+          git add .
+          git fetch --all
+          git checkout master
+          git checkout -b "$BRANCH"
+          git commit -m "[course-info][bot] Automatically update course JSON" || echo "Empty commit."
+          git push -f origin "$BRANCH" || git push -f --set-upstream origin "$BRANCH"
+      # Compare this against so that the later step can use the failure status
+      - name: Compare JSON against current JSON
+        run: diff a.json b.json
+      - name: Automatically create PR if JSON is different
+        uses: actions/github-script@0.2.0
+        if: failure()
+        with:
+          github-token: ${{ secrets.BOT_TOKEN }}
+          script: |
+            github.pulls.create({
+              owner: 'cornell-dti',
+              repo: 'samwise',
+              title: '[course-info][bot] Automatically update course JSON',
+              base: 'master',
+              head: 'dti-github-bot/update-course-json'
+            });
